INSERT INTO `person` (`id`, `nome`, `sobrenome`, `endereco`, `genero`) VALUES
(1, 'Lucas', 'Silva', 'São Paulo', 'Homem'),
(2, 'Julia', 'Santos', 'Rio de Janeiro', 'Mulher'),
(3, 'Pedro', 'Oliveira', 'Belo Horizonte', 'Homem'),
(4, 'Mariana', 'Souza', 'Salvador', 'Mulher'),
(5, 'Gabriel', 'Rodrigues', 'Curitiba', 'Homem'),
(6, 'Beatriz', 'Ferreira', 'Porto Alegre', 'Mulher'),
(7, 'Mateus', 'Alves', 'Recife', 'Homem'),
(8, 'Ana', 'Pereira', 'Fortaleza', 'Mulher'),
(9, 'Carlos', 'Lima', 'Florianópolis', 'Homem'),
(10, 'Laura', 'Gomes', 'Vitória', 'Mulher'),
(11, 'João', 'Costa', 'São Paulo', 'Homem'),
(12, 'Sofia', 'Ribeiro', 'Rio de Janeiro', 'Mulher'),
(13, 'Rafael', 'Martins', 'Belo Horizonte', 'Homem'),
(14, 'Camila', 'Almeida', 'Salvador', 'Mulher'),
(15, 'Antônio', 'Nunes', 'Curitiba', 'Homem'),
(16, 'Isabela', 'Carvalho', 'Porto Alegre', 'Mulher'),
(17, 'Francisco', 'Mendes', 'Recife', 'Homem'),
(18, 'Leticia', 'Barbosa', 'Fortaleza', 'Mulher'),
(19, 'Daniel', 'Castro', 'Florianópolis', 'Homem'),
(20, 'Gabriela', 'Teixeira', 'Vitória', 'Mulher');